// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hoa-cobalt/Dashboard.tsx": () => import("../components/mockups/hoa-cobalt/Dashboard.tsx"),
  "./components/mockups/hoa-cobalt-briefing/Dashboard.tsx": () => import("../components/mockups/hoa-cobalt-briefing/Dashboard.tsx"),
  "./components/mockups/hoa-cobalt-calendar/Dashboard.tsx": () => import("../components/mockups/hoa-cobalt-calendar/Dashboard.tsx"),
  "./components/mockups/hoa-cobalt-spatial/Dashboard.tsx": () => import("../components/mockups/hoa-cobalt-spatial/Dashboard.tsx"),
  "./components/mockups/hoa-cobalt-triage/Dashboard.tsx": () => import("../components/mockups/hoa-cobalt-triage/Dashboard.tsx"),
  "./components/mockups/hoa-fmt-focus/Dashboard.tsx": () => import("../components/mockups/hoa-fmt-focus/Dashboard.tsx"),
  "./components/mockups/hoa-fmt-wall/Dashboard.tsx": () => import("../components/mockups/hoa-fmt-wall/Dashboard.tsx"),
  "./components/mockups/hoa-fmt-chat/Dashboard.tsx": () => import("../components/mockups/hoa-fmt-chat/Dashboard.tsx"),
  "./components/mockups/hoa-quail/Dashboard.tsx": () => import("../components/mockups/hoa-quail/Dashboard.tsx"),
  "./components/mockups/hoa-forest/Dashboard.tsx": () => import("../components/mockups/hoa-forest/Dashboard.tsx"),
  "./components/mockups/hoa-vibe-dense/Dashboard.tsx": () => import("../components/mockups/hoa-vibe-dense/Dashboard.tsx"),
  "./components/mockups/hoa-vibe-quiet/Dashboard.tsx": () => import("../components/mockups/hoa-vibe-quiet/Dashboard.tsx"),
  "./components/mockups/hoa-vibe-soft/Dashboard.tsx": () => import("../components/mockups/hoa-vibe-soft/Dashboard.tsx")
};
